export const fetchTags = {
  qrCodes: "qr-codes",
  users: "users",
  auth: "auth",
  logos: "logos",
  qrCodeControllers: "qr-code-controllers",
  qrCodeQuantity: "qr-code-quantity",
  qrCodeStats: "qr-code-stats",
  topQrCodes: "top-qr-codes",
  qrCodeScans: "qr-code-scans",
  qrCodesWithScans: "qr-codes-with-scans",
  recentScans: "recent-scans",
  deviceUsage: "device-usage",
  scanLocations: "scan-locations",
  qrCodeAnalytics: "qr-code-analytics",
};
